#ifndef UNTITLED5_COMMON_H
#define UNTITLED5_COMMON_H

#include <QString>

extern const QChar separator;
QString& operator<< (QString& m, const QString& s);

enum messages {
   PRINT_POLYNOM_REQUEST,
   PRINT_POLYNOM_ANSWER,
   ADD_LEAD_COEFFICIENT_REQUEST,
   ADD_LEAD_COEFFICIENT_ANSWER,
   ADD_ROOT_REQUEST,
   ADD_ROOT_ANSWER,
   RESIZE_POLYNOM_REQUEST,
   RESIZE_POLYNOM_ANSWER,
   CHANGE_ROOT_REQUEST,
   CHANGE_ROOT_ANSWER,
   VALUE_AT_POINT_REQUEST,
   VALUE_AT_POINT_ANSWER
};

#endif //UNTITLED5_COMMON_H